<?php namespace Ophp\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:37:12.
 */
class HttpUtilsGetLocaleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Ophp\Http\HttpUtils
     * @group specification
     */
    public function testGetLocaleFromHttp()
    {
        $header  = 'Accept-Language: da, en-gb;q=0.8, en;q=0.7';
        $allowed = [ 1.2, TRUE, [ ], new \stdClass() ];
        $this->assertSame( 'en_GB', \Ophp\Http\HttpUtils::getLocale( $header, $allowed ) );
    }

    /**
     * @covers Ophp\Http\HttpUtils
     * @group specification
     */
    public function testGetLocaleFromDefault()
    {
        $header  = 'Accept-Language: q=0.8;q=0.7';
        $allowed = [ 'de-DE', 'fr-FR', 'en-US' ];
        $this->assertSame( 'de_DE', \Ophp\Http\HttpUtils::getLocale( $header, $allowed ) );
    }

    /**
     * @covers Ophp\Http\HttpUtils
     * @group specification
     */
    public function testGetLocale()
    {
        $header  = 'Accept-Language: en, en-US, en-cockney, i-cherokee, x-pig-latin';
        $allowed = [ 'de-DE', 'en-US' ];
        $this->assertSame( 'en_us', \Ophp\Http\HttpUtils::getLocale( $header, $allowed ) );
    }

    /**
     * @covers Ophp\Http\HttpUtils
     * @group specification
     */
    public function testGetBestLocale()
    {
        $header  = 'Accept-Language: fr-BE, fr-CH';
        $allowed = [ 'de-DE', 'fr-FR', 'en-US' ];
        $this->assertSame( 'fr_FR', \Ophp\Http\HttpUtils::getLocale( $header, $allowed ) );
    }

}
