<?php namespace OseilleTest\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:37:12.
 */
class HttpUtilsGetBestAllowedLocaleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testParametersAreEmpty()
    {
        $locale  = '';
        $allowed = [ ];
        $this->assertSame('', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testLocaleIsEmpty()
    {
        $locale  = '';
        $allowed = [ 'de-DE' ];
        $this->assertSame('de_DE', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testAllowedLocalesArrayIsEmpty()
    {
        $locale  = 'de-DE';
        $allowed = [ ];
        $this->assertSame('', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testGetBestMatch()
    {
        $locale  = 'de-DE-1996-x-prv1-prv2';
        $allowed = [ 'de-DEVA', 'de-DE-1996', 'de', 'de-DE' ];
        $this->assertSame('de_de_1996', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testGetBestOne()
    {
        $locale  = 'de-DEVA';
        $allowed = [ 'fr-FR', 'de-DE', 'en-US' ];
        $this->assertSame('de_DE', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }

    /**
     * @covers Oseille\Http\HttpUtils::getBestAllowedLocale
     * @group specification
     */
    public function testGetDefault()
    {
        $locale  = 'de';
        $allowed = [ 'en-US', 'fr-FR' ];
        $this->assertSame('en_US', \Oseille\Http\HttpUtils::getBestAllowedLocale($locale, $allowed));
    }
}
