<?php namespace Ophp\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:37:12.
 */
class HttpUtilsIsMSIETest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Ophp\Http\HttpUtils::isMSIE
     * @group specification
     */
    public function testUserAgentIsEmpty()
    {
        $header = ' ';
        $this->assertFalse(\Ophp\Http\HttpUtils::isMSIE($header));
    }

    /**
     * @covers Ophp\Http\HttpUtils::isMSIE
     * @group specification
     */
    public function testUserAgentIsNotValid()
    {
        $header = 'Mozilla/1.22 (compatible; MSIE ; Windows 3.1)';
        $this->assertFalse(\Ophp\Http\HttpUtils::isMSIE($header));
    }

    /**
     * @covers Ophp\Http\HttpUtils::isMSIE
     * @group specification
     */
    public function testUserAgentIsNotMsie()
    {
        $aHeaders = [
            'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0',
            'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
            'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0) Opera 12.14',
            'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
        ];
        foreach ($aHeaders as $sHeader) {
            $this->assertFalse(\Ophp\Http\HttpUtils::isMSIE($sHeader));
        }
    }

    /**
     * @covers Ophp\Http\HttpUtils::isMSIE
     * @group specification
     */
    public function testIsTrident()
    {
        $header = 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko';
        $this->assertTrue(\Ophp\Http\HttpUtils::isMSIE($header));
    }

    /**
     * @covers Ophp\Http\HttpUtils::isMSIE
     * @group specification
     */
    public function testIsMsie()
    {
        $header = 'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko';
        $this->assertTrue(\Ophp\Http\HttpUtils::isMSIE($header));
    }

}
